apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-order-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-order-producer
  template:
    metadata:
      labels:
        app: java-order-producer
    spec:
      containers:
        - name: java-order-producer
          image: danie-carbondatasolutions/order-producer-service:latest
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: ORDER_TOPIC
              value: "order.placed"
            - name: PRODUCER_INTERVAL_MS
              value: "2000"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-payment-service
  template:
    metadata:
      labels:
        app: java-payment-service
    spec:
      containers:
        - name: java-payment-service
          image: danie-carbondatasolutions/payment-service:latest
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: ORDER_TOPIC
              value: "order.placed"
            - name: PAYMENT_SUCCESS_TOPIC
              value: "payment.succeeded"
            - name: PAYMENT_FAILED_TOPIC
              value: "payment.failed"
            - name: PAYMENT_DLQ_TOPIC
              value: "payment.dlq"
            - name: CONSUMER_GROUP_ID
              value: "payment-processor-group"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-inventory-service
  template:
    metadata:
      labels:
        app: java-inventory-service
    spec:
      containers:
        - name: java-inventory-service
          image: danie-carbondatasolutions/inventory-service:latest
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: PAYMENT_SUCCESS_TOPIC
              value: "payment.succeeded"
            - name: INVENTORY_DLQ_TOPIC
              value: "inventory.dlq"
            - name: CONSUMER_GROUP_ID
              value: "inventory-updater-group"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
